version: '3'
services:
#  mysql:
#   container_name: some-mysql
#   image: mysql/mysql-server:5.7
#   environment:
#    MYSQL_DATABASE: test
#    MYSQL_ROOT_PASSWORD: hellokoding
#    MYSQL_ROOT_HOST: '%'
#   ports:
#   - "3306:3306"
#   restart: always

  toktalk:
    restart: always
    image: docker.sys/toktalk
    environment:
      SPRING_PROFILES_ACTIVE: local
    restart: always
    volumes:
    - /upload:/tmp
    ports:
    - 9090:9090
    depends_on:
      - rabbitmq
      - redis
    network_mode: host

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=test
    restart: unless-stopped
    network_mode: host

  redis:
    image: redis
    restart: unless-stopped
    network_mode: host

  nginx:
    image: nginx:1.13
    restart: always
    ports:
    - 80:80
    - 443:443
    volumes:
    - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
     - toktalk
    network_mode: host